apiVersion: apps/v1
kind: Deployment
metadata:
  name: n2-backend
  namespace: n2-durum
  labels:
    app: n2-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: n2-backend
  template:
    metadata:
      labels:
        app: n2-backend
    spec:
      containers:
        - name: backend
          image: n2-backend:0.2.0
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: PGHOST
              value: n2-db
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              valueFrom:
                secretKeyRef: { name: n2-db-secret, key: DB_USER }
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef: { name: n2-db-secret, key: DB_PASSWORD }
            - name: PGDATABASE
              valueFrom:
                secretKeyRef: { name: n2-db-secret, key: DB_NAME }
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: n2-backend
  namespace: n2-durum
spec:
  selector:
    app: n2-backend
  ports:
    - port: 3000
      targetPort: http