apiVersion: v1
kind: Service
metadata:
  name: n2-durum-sayfasi
  namespace: n2-durum
  labels:
    app: n2-durum-sayfasi
spec:
  type: ClusterIP
  selector:
    app: n2-durum-sayfasi
  ports:
    - name: http
      port: 80
      targetPort: http
